name: teflink_acore
description: A basic framework.
# version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  teflink_core:
    git:
      url: https://github.com/TeFlink/core.git
      ref: master
    # path: ../core

dev_dependencies:
  pedantic: ^1.8.0
  test: ^1.6.0
